### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/312a69fe-442f-4c7b-9d78-b15b273f03b2

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=crime

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM MOVIES",
    "movie_title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Cappola",
    "duration": 175,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": ["Crime", "Drama"]
}

### Borrar una película
DELETE http://localhost:1234/movies/4edfa574-9b00-4019-ad84-a02ec9fc8657

### Actualizar una película
PATCH http://localhost:1234/movies/f28e0491-2514-462e-ab35-b2811e69f80d
Content-Type: application/json

{
    "year": 2022
}