### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/312a69fe-442f-4c7b-9d78-b15b273f03b2

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=action

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM MOVIES",
    "movie_title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Cappola",
    "duration": 175,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": ["Crime", "Drama"]
}

### Borrar una película
DELETE http://localhost:1234/movies/0db13f6d-31f0-11f0-a5e5-00155da677c1

### Actualizar una película
PATCH http://localhost:1234/movies/9d305a3d-14c4-11f0-b0c7-00155d10545a
Content-Type: application/json

{
    "year": 2022
}